#!/bin/sh

# Update package list
sudo apt-get update

# Install dependencies
sudo apt-get install -y libxss1 libappindicator1 libindicator7 wget

# Download Google Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# Install Google Chrome
sudo apt install -y ./google-chrome-stable_current_amd64.deb

# Clean up
rm google-chrome-stable_current_amd64.deb
